name: ML Assignment CI

on:
  push:
    branches: [ dtree, kernelridge, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DecisionTree model
        run: |
          if [ -f train.py ]; then python train.py; fi

      - name: Run KernelRidge model
        run: |
          if [ -f train2.py ]; then python train2.py; fi
